config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories, :expenses, :users, :splash
  
  # Defines the root path route ("/")\
  root 'categories#index'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :expenses

  validates :name, presence: true, uniqueness: { scope: :user }
  validates :icon, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon).with_defaults(user_id: current_user.id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<!DOCTYPE html>
<nav class="navbar navbar-dark bg-primary">
<div class="container-fluid">
<h2 class="navbar-brand">
<%= category.icon %><%= category.name %>
</h2>
  </div>
</nav>
<br>
<div class="hstack gap-3">
  <div class="bg-light border">Total Spent:</div>
  <div class="bg-light border ms-auto"><%= number_to_currency(category.expenses.sum(:price)) %>
  
  </div>
  </div>
  <%= link_to "Add expense", new_expense_path, class: 'gap-3' %>
<br>

<% category.expenses.each do |expense| %>
<div class="hstack gap-3">
  <%= expense.title %>
  <div class="ms-auto">
  <%= expense.price %>
  </div>
  </div>
  </div>
  <%= link_to "Add expense", new_expense_path, class: 'gap-3' %>
  <% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.select :icon, [['🎲'], ['🚘'], ['🛒'], ['🍕'], ['📚'], ['🎞️'], ['🎶'], ['🍎'],
     ['👾'], ['✍🏽'], ['🏃🏽'], ['❤️'], ['⭐'], ['🐶'], ['🌳'], ['🌎'], ['🌙'], ['💧'], ['☀️'],
      ['🌹'], ['🏈'], ['🥊'], ['✈️'], ['🏕️'], ['🚲'], ['🔨'], ['📆'], ['📎'], ['🔒'], ['📌'], ['✂️'],
       ['🕙'], ['🧹']] %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <div class="hstack gap-3">
  <div><%= category.icon %><%=  link_to category.name, category %>
  </div>
  <div class="ms-auto"><%= number_to_currency(category.expenses.sum(:price)) %></div>
  </div>
  </div>
    
    <%= link_to "View Expense", category, class: 'gap-3' %><br>
    <br>
    </div>
    <% end %>
    <br>
<div class="footer">
<%= link_to "New category", new_category_path, class: "btn btn-outline-light" %>
<br>
<br>
<% if user_signed_in? %>
<%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-dark" %> 
<% else %>
<%= link_to "Splash", splash_index_path, class: "btn btn-outline-success" %><br>
<% end %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>
<br>
<div class= "footer">
  <%= link_to "Back to categories", categories_path, class: "btn btn-outline-light" %> |
  <%= link_to "Edit this category", edit_category_path(@category), class: "btn btn-outline-light" %> |

  <%= button_to "Destroy this category", @category, method: :delete, class: "btn btn-outline-light" %>
</div>