config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories, :expenses, :users, :splash
  
  # Defines the root path route ("/")\
  root 'categories#index'
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: %i[show edit update destroy]
  before_action :set_category

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)
    respond_to do |format|
      if @expense.save
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:title, :price, :category_id).with_defaults(user_id: current_user.id)
  end

  def set_category
    @category = Category.where(params[:category_id]).order(:name)
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
  <div class="bg-light border"> <%= link_to expense.category.name, expense.category %>
  </div>
  <div class="hstack gap-3">
  <%= expense.title %>
  <div class="ms-auto"><%= expense.price %></div><br>
  </div>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category_id, options_for_select(@category.collect { |cat| [cat.name, cat.id]}) %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenses</h1>

<div class="hstack gap-3"> 
Total expenses
<div class="ms-auto">
<%= number_to_currency(@expenses.sum(:price)) %>
</div>
</div>

<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render expense %>
    <p>
      <%= link_to "Show this expense", expense, class:'gap-3' %>
    </p>
  <% end %>
</div>

<div class= 'footer'>
<%= link_to "New expense", new_expense_path, class: "btn btn-outline-light" %>
<br>
<% if user_signed_in? %>
<%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-dark" %> 
<% else %>
<%= link_to "Splash", splash_index_path, class: "btn btn-outline-success" %><br>
 </div>
 <% end %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div class='footer'>
  <%= link_to "Edit this expense", edit_expense_path(@expense), class: "btn btn-outline-light" %> |
  <%= link_to "Back to categories", categories_path, class: "btn btn-outline-light" %> |

  <%= button_to "Destroy this expense", @expense, method: :delete, class: "btn btn-outline-light" %>
</div>